import type { Readable } from 'node:stream';

/**
 * Object storage behind one interface (spec §47).
 *
 * Keys are opaque and generated by the service layer — they are never derived
 * from a user-supplied filename and never leave the server. Downloads always go
 * through an authorised API route, so a storage path cannot become a shareable
 * link that bypasses permission checks.
 */
export interface StoredObject {
  key: string;
  sizeBytes: number;
  /** SHA-256 of the stored bytes, for integrity and duplicate detection. */
  checksumSha256: string;
}

export interface PutOptions {
  contentType: string;
  /** Original filename, used only for the Content-Disposition on download. */
  fileName?: string;
}

export interface StorageProvider {
  readonly driver: 'local' | 's3';

  put(key: string, body: Buffer, options: PutOptions): Promise<StoredObject>;
  get(key: string): Promise<Readable>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
}

/**
 * Builds a storage key. The extension is preserved for content-type sniffing
 * on the way back out; everything identifying is a UUID, so the key leaks
 * nothing about the customer or the document even if it is somehow observed.
 */
export function buildStorageKey(parts: {
  scope: string;
  scopeId: string;
  documentId: string;
  extension: string;
}): string {
  const ext = parts.extension.replace(/[^a-z0-9.]/gi, '').toLowerCase();
  return `${parts.scope}/${parts.scopeId}/${parts.documentId}${ext.startsWith('.') ? ext : `.${ext}`}`;
}
